services:
  app:
    build: .
    ports:
      - "3000:3000"   # backend
      - "5173:5173"   # frontend (vite dev server)
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    restart: unless-stopped
